<?php

namespace Database\Seeders;

use App\Models\RecordsDispositionSchedule;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RDSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $rds = [
            [
                "id" => "1",
                "item_number" => "1",
                "record_series_title_and_description" => "AUDIT DOCUMENTATION",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "AFTER AUDIT",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:14:09",
                "updated_at" => "2025-02-05 18:14:09",
            ],
            [
                "id" => "2",
                "item_number" => "2",
                "record_series_title_and_description" => "BUSINESS CONTINUITY PLAN",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "PROVIDED UPDATED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:17:23",
                "updated_at" => "2025-02-05 18:17:23",
            ],
            [
                "id" => "3",
                "item_number" => "3",
                "record_series_title_and_description" =>
                "COMMUNICATIONS/CORRESPONDENCE (EXTERNAL/INTERNAL)",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "TO BE FILLED WITH APPROPRIATE RECORDS SERIES",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:19:57",
                "updated_at" => "2025-02-05 18:19:57",
            ],
            [
                "id" => "4",
                "item_number" => "4",
                "record_series_title_and_description" => "CONSUMPTION REPORTS",
                "record_series_title_and_description_1" =>
                "ELECTRICITY, PAPER, WATER",
                "active" => "1",
                "storage" => "0",
                "remarks" => "",
                "has_condition" => "0",
                "created_at" => "2025-02-05 18:20:41",
                "updated_at" => "2025-02-05 18:20:41",
            ],
            [
                "id" => "5",
                "item_number" => "5",
                "record_series_title_and_description" =>
                "COURIER/TRANSMITTAL SLIPS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "",
                "has_condition" => "0",
                "created_at" => "2025-02-05 18:21:15",
                "updated_at" => "2025-02-05 18:21:15",
            ],
            [
                "id" => "6",
                "item_number" => "6",
                "record_series_title_and_description" => "DIRECTIVES/ISSUANCES",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "AFTER SUPERSEDED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:32:39",
                "updated_at" => "2025-02-05 18:32:39",
            ],
            [
                "id" => "7",
                "item_number" => "7",
                "record_series_title_and_description" => "LOGBOOKS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "AFTER DATE OF LAST ENTRY",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:33:16",
                "updated_at" => "2025-02-05 18:33:16",
            ],
            [
                "id" => "8",
                "item_number" => "8",
                "record_series_title_and_description" => "MANUALS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER SUSPERSEDED PROVIDED DIGITIZED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:34:15",
                "updated_at" => "2025-02-05 18:34:15",
            ],
            [
                "id" => "9",
                "item_number" => "9",
                "record_series_title_and_description" => "MEETING FILES",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER AUDIT",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:46:54",
                "updated_at" => "2025-02-05 18:46:54",
            ],
            [
                "id" => "10",
                "item_number" => "10",
                "record_series_title_and_description" =>
                "PLANNING CONFERENCE FILES",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 18:51:56",
                "updated_at" => "2025-02-05 18:51:56",
            ],
            [
                "id" => "11",
                "item_number" => "11",
                "record_series_title_and_description" => "REPORTS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 18:52:23",
                "updated_at" => "2025-02-05 18:52:23",
            ],
            [
                "id" => "12",
                "item_number" => "12",
                "record_series_title_and_description" =>
                "RISK CONTROL SELF ASSESSMENT (RCSA) MATRICES",
                "record_series_title_and_description_1" => null,
                "active" => "3",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 18:53:21",
                "updated_at" => "2025-02-05 18:53:21",
            ],
            [
                "id" => "13",
                "item_number" => "13",
                "record_series_title_and_description" =>
                "SIOURCE, INPUT, PROCESS, OUTPUT, CLIENT (SIPOC) RECORDS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 18:53:59",
                "updated_at" => "2025-02-05 18:53:59",
            ],
            [
                "id" => "14",
                "item_number" => "14",
                "record_series_title_and_description" =>
                "TRAINING/SEMINAR/BROCHURES/REFERENCE MATERIALS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER SUPERSEDED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 18:55:07",
                "updated_at" => "2025-02-05 18:55:07",
            ],
            [
                "id" => "15",
                "item_number" => "15",
                "record_series_title_and_description" => "BOND FILES",
                "record_series_title_and_description_1" =>
                " (ACTION , APPLICATION LETTER, INDEMNITY, LIST OF BONDED PERSONNEL)",
                "active" => "3",
                "storage" => "0",
                "remarks" => "AFTER EXPIRATION",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:02:41",
                "updated_at" => "2025-02-05 19:02:41",
            ],
            [
                "id" => "16",
                "item_number" => "15B",
                "record_series_title_and_description" => "BOND FILES",
                "record_series_title_and_description_1" => "FIDELITY/SURETY",
                "active" => "5",
                "storage" => "0",
                "remarks" => "AFTER EXPIRATION",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:03:40",
                "updated_at" => "2025-02-05 19:03:40",
            ],
            [
                "id" => "17",
                "item_number" => "16",
                "record_series_title_and_description" => "BUDGET FILES",
                "record_series_title_and_description_1" =>
                "PROPOSAL, TRANSFER REQUEST/ADVICE, VARIANCE REPORTS",
                "active" => "1",
                "storage" => "0",
                "remarks" => "",
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:04:54",
                "updated_at" => "2025-02-05 19:04:54",
            ],
            [
                "id" => "18",
                "item_number" => "17",
                "record_series_title_and_description" =>
                "MONTHLY REPORT ON REVENUE AND EXPENSE",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:05:26",
                "updated_at" => "2025-02-05 19:05:26",
            ],
            [
                "id" => "19",
                "item_number" => "18",
                "record_series_title_and_description" => "PETTY CASH",
                "record_series_title_and_description_1" =>
                "CASH BOOK, REPLENISHMENT REPORT, SUMMARY OF EXPENSE",
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER DATE OF LAST ENTRY AND AUDITED ",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:06:23",
                "updated_at" => "2025-02-05 19:06:23",
            ],
            [
                "id" => "20",
                "item_number" => "19",
                "record_series_title_and_description" =>
                "REPORT ON EXPENSE PAID BY OTHER BANK UNITS",
                "record_series_title_and_description_1" => "REPOBU",
                "active" => "1",
                "storage" => "0",
                "remarks" => "",
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:07:08",
                "updated_at" => "2025-02-05 19:07:08",
            ],
            [
                "id" => "21",
                "item_number" => "20",
                "record_series_title_and_description" => "APPLICATION FOR LEAVE",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" =>
                "AFTER SUBMISSION OF MONTHLY ATTENDANCE REPORT TO PAD FOR THE SAP HRIS",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:08:53",
                "updated_at" => "2025-02-05 19:08:53",
            ],
            [
                "id" => "22",
                "item_number" => "21",
                "record_series_title_and_description" => "ATTENDANCE SHEET/BLOTTER",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:09:20",
                "updated_at" => "2025-02-05 19:09:20",
            ],
            [
                "id" => "23",
                "item_number" => "22",
                "record_series_title_and_description" =>
                "AUTHORITY TO RENDER OVERTIME",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:09:49",
                "updated_at" => "2025-02-05 19:09:49",
            ],
            [
                "id" => "24",
                "item_number" => "23",
                "record_series_title_and_description" =>
                "AUTHORIZATION TO GO ON OFFICIAL BUSINESS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:10:12",
                "updated_at" => "2025-02-05 19:10:12",
            ],
            [
                "id" => "25",
                "item_number" => "24",
                "record_series_title_and_description" =>
                "CERTIFICATE OF APPEARANCE",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:10:31",
                "updated_at" => "2025-02-05 19:10:31",
            ],
            [
                "id" => "26",
                "item_number" => "25",
                "record_series_title_and_description" =>
                "CLAIM FOR OVERTIME AND NIGHT DIFFERENTIAL",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:11:01",
                "updated_at" => "2025-02-05 19:11:01",
            ],
            [
                "id" => "27",
                "item_number" => "26",
                "record_series_title_and_description" => "DAILY TIME RECORD",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" =>
                "AFTER SUBMISSION OF MONTHLY ATTENDANCE REPORT TO PAD FOR SAP HRIS",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:11:42",
                "updated_at" => "2025-02-05 19:11:42",
            ],
            [
                "id" => "28",
                "item_number" => "27",
                "record_series_title_and_description" => "EMPLOYEE CLEARANCE",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:12:02",
                "updated_at" => "2025-02-05 19:12:02",
            ],
            [
                "id" => "29",
                "item_number" => "28",
                "record_series_title_and_description" =>
                "MONTHLY ATTENDANCE/ INVENTORY RFEPORT",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:12:30",
                "updated_at" => "2025-02-05 19:12:30",
            ],
            [
                "id" => "30",
                "item_number" => "29",
                "record_series_title_and_description" =>
                "OFFICERS DAILY ATTENDANCE LOGBOOK",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:12:57",
                "updated_at" => "2025-02-05 19:12:57",
            ],
            [
                "id" => "31",
                "item_number" => "30",
                "record_series_title_and_description" => "OFFICERS  TIME RECORD",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:13:12",
                "updated_at" => "2025-02-05 19:13:12",
            ],
            [
                "id" => "32",
                "item_number" => "31",
                "record_series_title_and_description" =>
                "AUTHORITY TO WITHDRAW SUPPLIES",
                "record_series_title_and_description_1" => null,
                "active" => "6",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:15:27",
                "updated_at" => "2025-02-05 19:15:27",
            ],
            [
                "id" => "33",
                "item_number" => "32",
                "record_series_title_and_description" =>
                "CERTIFICATE OF DISPOSAL RECORDS",
                "record_series_title_and_description_1" => null,
                "active" => "99999999999",
                "storage" => "999999999",
                "remarks" => "PERMANENT",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:16:11",
                "updated_at" => "2025-02-05 19:16:11",
            ],
            [
                "id" => "34",
                "item_number" => "33",
                "record_series_title_and_description" =>
                "CERTIFICATION OF ACCESS RIGHTS FORM FOR ENROLLMENT/ USERS REQUEST",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:16:57",
                "updated_at" => "2025-02-05 19:16:57",
            ],
            [
                "id" => "35",
                "item_number" => "34",
                "record_series_title_and_description" => "INVENTORY FILES",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER UPDATED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:17:24",
                "updated_at" => "2025-02-05 19:17:24",
            ],
            [
                "id" => "36",
                "item_number" => "35",
                "record_series_title_and_description" =>
                "INVOICE RECEIPTS FOR PROPERTIES",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "AFTER DISPOSAL OF PROPERTY",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:18:03",
                "updated_at" => "2025-02-05 19:18:03",
            ],
            [
                "id" => "37",
                "item_number" => "36",
                "record_series_title_and_description" => "JOB ORDER REQUEST",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER ACTED UPON",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:18:26",
                "updated_at" => "2025-02-05 19:18:26",
            ],
            [
                "id" => "38",
                "item_number" => "37",
                "record_series_title_and_description" =>
                "MEMORANDUM RECEIPTS FOR EQUIPMENT, SEMI EXPENDABLE AND NON- EXPENDABLE PROPERTY",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER CANCELLATION OF MR",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:19:29",
                "updated_at" => "2025-02-05 19:19:29",
            ],
            [
                "id" => "39",
                "item_number" => "38",
                "record_series_title_and_description" =>
                "PREVENTIVE SERVICE MAINTENANCE AGREEMENT",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER TERMINATION / EXPIRATION",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:20:28",
                "updated_at" => "2025-02-05 19:20:28",
            ],
            [
                "id" => "40",
                "item_number" => "39",
                "record_series_title_and_description" =>
                "PROCUREMENT REQUEST FORM /. REQUISITION ISSUE VOUCHER",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:21:01",
                "updated_at" => "2025-02-05 19:21:01",
            ],
            [
                "id" => "41",
                "item_number" => "40",
                "record_series_title_and_description" => "PROPERTY TRANSFER SLIPS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:22:14",
                "updated_at" => "2025-02-05 19:22:14",
            ],
            [
                "id" => "42",
                "item_number" => "41",
                "record_series_title_and_description" =>
                "RECORDS DISPOSITION SCHEDULE",
                "record_series_title_and_description_1" => null,
                "active" => "10",
                "storage" => "0",
                "remarks" => "AFTER SUPERSEDED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:22:43",
                "updated_at" => "2025-02-05 19:22:43",
            ],
            [
                "id" => "43",
                "item_number" => "42A",
                "record_series_title_and_description" => "REPORTS",
                "record_series_title_and_description_1" =>
                "(INVENTORY AND INSPECTION  OF UNSERVICEABLE PROPERTIES)",
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER PROPERTY HAS BEEN DISPOSED ",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:23:59",
                "updated_at" => "2025-02-05 19:23:59",
            ],
            [
                "id" => "44",
                "item_number" => "42B",
                "record_series_title_and_description" => "REPORTS",
                "record_series_title_and_description_1" =>
                "(PROPERTY DISPOSAL , SYSTEM INCIDENT, WASTE MATERIAL)",
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER ACTED UPON ",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:24:38",
                "updated_at" => "2025-02-05 19:24:38",
            ],
            [
                "id" => "45",
                "item_number" => "43",
                "record_series_title_and_description" => "STOCK CARDS ON SUPPLIES",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "1",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:25:02",
                "updated_at" => "2025-02-05 19:25:02",
            ],
            [
                "id" => "46",
                "item_number" => "44",
                "record_series_title_and_description" => "STOCK POSITION SHEET",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 19:25:23",
                "updated_at" => "2025-02-05 19:25:23",
            ],
            [
                "id" => "47",
                "item_number" => "45A",
                "record_series_title_and_description" =>
                "TURNOVER LISTING AND DISPOSAL AUTHORITY",
                "record_series_title_and_description_1" => null,
                "active" => "99999999",
                "storage" => "0",
                "remarks" => "PERMANENT",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:26:05",
                "updated_at" => "2025-02-05 19:26:05",
            ],
            [
                "id" => "48",
                "item_number" => "45B",
                "record_series_title_and_description" =>
                "TURNOVER LISTING AND DISPOSAL AUTHORITY",
                "record_series_title_and_description_1" => "(TEMPORARY RECORDS)",
                "active" => "1",
                "storage" => "0",
                "remarks" => "AFTER DISPOSAL DATE AND AUDIT ",
                "has_condition" => "1",
                "created_at" => "2025-02-05 19:26:58",
                "updated_at" => "2025-02-05 19:26:58",
            ],
            [
                "id" => "49",
                "item_number" => "85",
                "record_series_title_and_description" =>
                "ABSTRACTS (PAYMENT AND REMITTANCE)",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "3",
                "remarks" => "PROVIDED AUDITED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 20:27:24",
                "updated_at" => "2025-02-05 20:27:24",
            ],
            [
                "id" => "50",
                "item_number" => "86",
                "record_series_title_and_description" =>
                "ACCOUNT OPENING SCREEN PRINT-OUTS (FIAS/RM)",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "2",
                "remarks" => "PROVIDED AUDITED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 20:28:48",
                "updated_at" => "2025-02-05 20:28:48",
            ],
            [
                "id" => "51",
                "item_number" => "88",
                "record_series_title_and_description" =>
                "ANTI-MONEY LAUNDERING ACT(AMLA) RELATED RECORDS",
                "record_series_title_and_description_1" =>
                "AMLA - DATA ENTRY SYSTEM TRANSACTION RECORDS\\nQUARTERLY CERTIFICATION\\nREPORTS\\n	COVERED TRANSACTION (CTR)\\n	SUSPICIOUS TRANSACTION (STR)\\nSAS ALERTS",
                "active" => "1",
                "storage" => "4",
                "remarks" => "PROVIDED AUDITED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 20:44:28",
                "updated_at" => "2025-02-05 20:44:28",
            ],
            [
                "id" => "52",
                "item_number" => "89",
                "record_series_title_and_description" =>
                "APPLICATION (Demand Draft/Electronic Money Transfer/ Gift Checks/ Manager\\\'s Checks/ Traveller\\\'s Check/ Outgoing Telegraphic Transfer)",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "4",
                "remarks" => "Provided Negotiated",
                "has_condition" => "1",
                "created_at" => "2025-02-05 20:49:42",
                "updated_at" => "2025-02-05 20:49:42",
            ],
            [
                "id" => "53",
                "item_number" => "90",
                "record_series_title_and_description" =>
                "AUTHORITY FOR FUND TRANSFER(Credit/Debit Memo)",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" =>
                "Accounting Center Copies shall be retained for 10 years",
                "has_condition" => "1",
                "created_at" => "2025-02-05 20:51:03",
                "updated_at" => "2025-02-05 20:51:03",
            ],
            [
                "id" => "54",
                "item_number" => "91",
                "record_series_title_and_description" => "AUTHORIZATION LETTERS",
                "record_series_title_and_description_1" =>
                "Bank Certificate\\nCheckbook\\nIncoming Returned Checks\\nSnap Shot",
                "active" => "1",
                "storage" => "2",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 20:52:15",
                "updated_at" => "2025-02-05 20:52:15",
            ],
            [
                "id" => "55",
                "item_number" => "93",
                "record_series_title_and_description" =>
                "AUTOMATED TELLER MACHINE (ATM) CARD REQUEST AND UPDATE FORMS(ACRUF) WITH SUPPORTING DOCUMENTS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "8",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 20:53:26",
                "updated_at" => "2025-02-05 20:53:26",
            ],
            [
                "id" => "56",
                "item_number" => "94",
                "record_series_title_and_description" =>
                "BRANH LOAN FILES(Livelihood and Hold-out)",
                "record_series_title_and_description_1" =>
                "Government/Judicial Entities\\nIndividual Borrower",
                "active" => "1",
                "storage" => "4",
                "remarks" =>
                "AFTER FULL PAYMENT AND FINAL SETTLEMENT TERMINATION OF LOAN",
                "has_condition" => "1",
                "created_at" => "2025-02-05 20:55:22",
                "updated_at" => "2025-02-05 20:55:22",
            ],
            [
                "id" => "57",
                "item_number" => "94",
                "record_series_title_and_description" =>
                "BUREAU OF CUSTOMS (BOC) FILES",
                "record_series_title_and_description_1" =>
                "Transaction Reports\\n     Cargo Transfer Fees(ASYCUDA)\\n      Revenue Accounting Division\\nElectronic to Mobile (e2M)/Additional Payment\\n   BOC Revenue Accounting Division \\nMonthly\\n   Reports\\n   Daily\\n   Detailed\\nPayment Application Secure System 5 (PASS 5)\\nReports\\n  Internet Generated Report on PASS \\n  5 Payment\\n  Summary on Daily Transaction on \\nPASS 5 Payment",
                "active" => "1",
                "storage" => "4",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 21:04:26",
                "updated_at" => "2025-02-05 21:04:26",
            ],
            [
                "id" => "58",
                "item_number" => "95",
                "record_series_title_and_description" =>
                "BUREAU OF INTERNAL REVENUE FILES",
                "record_series_title_and_description_1" =>
                "Electronic Documentary Stamp (eDST)\\n     Book of Documentary Stamp \\n     Daily Transaction\\n     Report on Sales/Usage of \\n     Documentary Stamps\\n     Summary of Documentary Stamp \\n      Tax Paid and\\n      Remitted\\nOver-the-Counter (OTC) Collections\\n      External Media Transmittal (Form 2840)\\n       Report of BIR Returned/Dishonored Checks\\n        Taxpayer’s Payment Batch Control Sheets (BCS)",
                "active" => "1",
                "storage" => "4",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 21:31:25",
                "updated_at" => "2025-02-05 21:31:25",
            ],
            [
                "id" => "59",
                "item_number" => "96",
                "record_series_title_and_description" => "CAUTION NOTICES",
                "record_series_title_and_description_1" =>
                "Foreign Bank Notes Alert\\n    Lost Certificate of Time Deposit (CTD)\\n    Lost Checks",
                "active" => "2",
                "storage" => "0",
                "remarks" => "After account closure",
                "has_condition" => "1",
                "created_at" => "2025-02-05 21:32:50",
                "updated_at" => "2025-02-05 21:32:50",
            ],
            [
                "id" => "60",
                "item_number" => "97",
                "record_series_title_and_description" => "CASH CARD APPLICATIONS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "8",
                "remarks" => "AFTER ACCOUNT CLOSURE",
                "has_condition" => "1",
                "created_at" => "2025-02-05 21:34:55",
                "updated_at" => "2025-02-05 21:34:55",
            ],
            [
                "id" => "61",
                "item_number" => "98",
                "record_series_title_and_description" => "CAUTION NOTICES",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 21:35:24",
                "updated_at" => "2025-02-05 21:35:24",
            ],
            [
                "id" => "62",
                "item_number" => "99",
                "record_series_title_and_description" => "CERTIFICATIONS",
                "record_series_title_and_description_1" =>
                "Deposit and Existing Account\\nIDRARS Branch Certification",
                "active" => "2",
                "storage" => "3",
                "remarks" => "PROVIDED AND AUDITED",
                "has_condition" => "1",
                "created_at" => "2025-02-05 21:36:15",
                "updated_at" => "2025-02-05 21:36:15",
            ],
            [
                "id" => "63",
                "item_number" => "100A",
                "record_series_title_and_description" => "CHECKBOOK REQUISITIONS",
                "record_series_title_and_description_1" => "Customer Request",
                "active" => "3",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 21:37:22",
                "updated_at" => "2025-02-05 21:37:22",
            ],
            [
                "id" => "64",
                "item_number" => "100B",
                "record_series_title_and_description" => "CHECKBOOK REQUISITION",
                "record_series_title_and_description_1" =>
                "Screen Print-out Application",
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:08:14",
                "updated_at" => "2025-02-05 22:08:14",
            ],
            [
                "id" => "65",
                "item_number" => "101",
                "record_series_title_and_description" => "CLIENT COMPLAINT FORM",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:08:33",
                "updated_at" => "2025-02-05 22:08:33",
            ],
            [
                "id" => "66",
                "item_number" => "102",
                "record_series_title_and_description" =>
                "CONFIRMATION OF SALES/PURCHASES OF GOVERNMENT/PRIVATE SECURITIES",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "4",
                "remarks" => "After Termination",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:09:05",
                "updated_at" => "2025-02-05 22:09:05",
            ],
            [
                "id" => "67",
                "item_number" => "103",
                "record_series_title_and_description" => "CORPORATE ACCOUNT FILES",
                "record_series_title_and_description_1" =>
                "Affidavit of Lost Passbook (if applicable)\\nArticle of Incorporation and By-Laws\\nBackground/Credit Investigation\\nBoard Resolution with Authorized Signatories and\\nAuthority to Open Account\\nBusiness Permit\\nCustomer Information and Specimen Signature Card\\nof Corporate Authorized Signatories with Supporting\\nDocuments\\nCustomer Information Sheet of Corporation\\nGeneral Information Sheet\\nRegistration Documents (e.g.SEC/DTI/CDA,etc.)\\nSecretary\\\'s Certificate",
                "active" => "1",
                "storage" => "4",
                "remarks" => "After Termination",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:09:52",
                "updated_at" => "2025-02-05 22:09:52",
            ],
            [
                "id" => "68",
                "item_number" => "104",
                "record_series_title_and_description" =>
                "DEPOSIT ACCOUNT ADJUSTMENTS (ST24) WITH SUPPORTING DOCUMENTS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => "After account closure",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:11:29",
                "updated_at" => "2025-02-05 22:11:29",
            ],
            [
                "id" => "69",
                "item_number" => "105",
                "record_series_title_and_description" =>
                "DORMANT DEPOSIT ACCOUNT FILES",
                "record_series_title_and_description_1" =>
                "Certificate of Mailing\\nList of Returned Mail\\nNotice to Depositor\\nNotice to Depositor of Impending Dormancy\\nProof of Mail Delivery\\nSchedules\\nDormant Deposit Accounts (SDDA)\\nNotice to Depositor of Impending Dormancy\\nNotice of Dormancy\\nUnclaimed Balances Accounts (SUBA)\\nSpecial Power ofAttorney (if applicable)\\nSworn Statement of Unclaimed Balances (SSUB)",
                "active" => "2",
                "storage" => "0",
                "remarks" => "After escheatment Provided audited",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:12:28",
                "updated_at" => "2025-02-05 22:12:28",
            ],
            [
                "id" => "70",
                "item_number" => "106",
                "record_series_title_and_description" =>
                "e-BANKING PRODUCTS ENROLMENT RECORDS",
                "record_series_title_and_description_1" =>
                "(Access\\nPhone Access\\nweAccess",
                "active" => "2",
                "storage" => "8",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:14:15",
                "updated_at" => "2025-02-05 22:14:15",
            ],
            [
                "id" => "71",
                "item_number" => "107",
                "record_series_title_and_description" =>
                "E-CARD APPLICATION (DATA CAPTURED)",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "8",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:14:42",
                "updated_at" => "2025-02-05 22:14:42",
            ],
            [
                "id" => "72",
                "item_number" => "1",
                "record_series_title_and_description" => "AUDITJHDJKHDKH",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:14:58",
                "updated_at" => "2025-02-05 22:14:58",
            ],
            [
                "id" => "73",
                "item_number" => "108",
                "record_series_title_and_description" =>
                "EURO SAVINGS LEDGER CARDS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "4",
                "remarks" => "After account closure",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:36:38",
                "updated_at" => "2025-02-05 22:36:38",
            ],
            [
                "id" => "74",
                "item_number" => "109",
                "record_series_title_and_description" => "EXCHANGE BOUGHT TICKETS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" =>
                "Accounting Center\\\'s copy shall be retained for 10 years",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:37:51",
                "updated_at" => "2025-02-05 22:37:51",
            ],
            [
                "id" => "75",
                "item_number" => "110",
                "record_series_title_and_description" =>
                "FOREIGN CURRENCY DEPOSIT UNIT (FCDU/PESO WIRE TRANSFER FILES",
                "record_series_title_and_description_1" =>
                "Application to Purchase\\nForeign Currencies (Dollar & 3rd Currencies)\\nPeso\\nCredit /Inter-Office Advice (IOA)\\nGross Settlement Real Time (GSRT) - Dollar to Dollar\\n(Local)\\nOutgoing Telegraphic Transfer (MT 103)\\nReal Time Gross Settlement (RTGS) - Peso to Peso\\n(Local)",
                "active" => "2",
                "storage" => "0",
                "remarks" =>
                "Accounting Center\\\'s copy shall be retained for 10 years",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:40:23",
                "updated_at" => "2025-02-05 22:40:23",
            ],
            [
                "id" => "76",
                "item_number" => "111",
                "record_series_title_and_description" =>
                "INCOMING CLEARING CHECKS (ICC) CONFIRMATION SHEETS WITH PHOTOCOPY OF CHECKS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "4",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:41:06",
                "updated_at" => "2025-02-05 22:41:06",
            ],
            [
                "id" => "77",
                "item_number" => "112",
                "record_series_title_and_description" => "INDIVIDUAL ACCOUNT FILES",
                "record_series_title_and_description_1" =>
                "Background/Credit Investigation\\nCustomer Information Sheet\\nCustomer Information and Specimen Signature Card\\nwith Supporting Documents\\nLetter of Introduction\\nPhotocopy of Valid Identification Card (ID)\\nSpecial Power of Attorney\\nForeign\\nLocal\\nPensioners",
                "active" => "1",
                "storage" => "4",
                "remarks" => "After account closure",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:41:37",
                "updated_at" => "2025-02-05 22:41:37",
            ],
            [
                "id" => "78",
                "item_number" => "113",
                "record_series_title_and_description" =>
                "INTERBRANCH CONFIRMATION ON DEPOSIT AND WITHDRAWALS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "4",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:41:58",
                "updated_at" => "2025-02-05 22:41:58",
            ],
            [
                "id" => "79",
                "item_number" => "114",
                "record_series_title_and_description" =>
                "INTER-DEPARTMENT TRANSACTION CONFIRMATION SHEETS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:42:12",
                "updated_at" => "2025-02-05 22:42:12",
            ],
            [
                "id" => "80",
                "item_number" => "115",
                "record_series_title_and_description" => "LEASE CONTRACTS",
                "record_series_title_and_description_1" => null,
                "active" => "3",
                "storage" => "2",
                "remarks" => "After termination and full settlement",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:42:39",
                "updated_at" => "2025-02-05 22:42:39",
            ],
            [
                "id" => "81",
                "item_number" => "116",
                "record_series_title_and_description" => "LOGBOOK",
                "record_series_title_and_description_1" =>
                "Accountable Form\\nAlarm Testing\\nATM Access\\nBank Statements (B/S)\\nCaptured Card\\nCheck Book Issuance\\nClient\\\'s Complaint\\nDemand Draft Issuance\\nDuplicate Keys\\nGift Check Issuance\\nIncoming Clearing Checks (ICC)\\nIncoming Returned Checks (IRC)\\nInstant Cards Registry\\nItems Held for Safekeeping/Collateral\\nLate Deposit\\nPassbook (Receiving)\\nReturned Checks and Other Clearing Items (RCOCI)\\nSafe Deposit Box Access\\nStop Payment Order (SPO)\\nSystem Access\\nVault Registry",
                "active" => "2",
                "storage" => "0",
                "remarks" => "After date of last entry",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:43:24",
                "updated_at" => "2025-02-05 22:43:24",
            ],
            [
                "id" => "82",
                "item_number" => "117",
                "record_series_title_and_description" => "MEMORANDA OF AGREEMENTS",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "3",
                "remarks" => "After termination/renewal",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:43:53",
                "updated_at" => "2025-02-05 22:43:53",
            ],
            [
                "id" => "83",
                "item_number" => "118",
                "record_series_title_and_description" =>
                "MODIFIED DISBURSEMENT SCHEME(MDS) FILES",
                "record_series_title_and_description_1" =>
                "Notice of Transfer Allocation (NTA)\\nSummary of Notice of Cash Allocation",
                "active" => "3",
                "storage" => "0",
                "remarks" => "Provided audited",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:44:55",
                "updated_at" => "2025-02-05 22:44:55",
            ],
            [
                "id" => "84",
                "item_number" => "119",
                "record_series_title_and_description" => "NEGOTIATED CHECKS",
                "record_series_title_and_description_1" =>
                "Demand Draft\\nGift Check\\nManager\\\'s Checks",
                "active" => "1",
                "storage" => "4",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:46:25",
                "updated_at" => "2025-02-05 22:46:25",
            ],
            [
                "id" => "85",
                "item_number" => "120",
                "record_series_title_and_description" =>
                "NOTICES/WARRANT OF GARNISHMENTS",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "0",
                "remarks" =>
                "After termination of case/\\nAfter receipt of Notice of Lifting",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:46:52",
                "updated_at" => "2025-02-05 22:46:52",
            ],
            [
                "id" => "86",
                "item_number" => "121A",
                "record_series_title_and_description" =>
                "OFFICIAL RECEIPTS (Branch Copy)",
                "record_series_title_and_description_1" => "LBP",
                "active" => "3",
                "storage" => "7",
                "remarks" => "Provided post-audited",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:47:26",
                "updated_at" => "2025-02-05 22:47:26",
            ],
            [
                "id" => "87",
                "item_number" => "121B",
                "record_series_title_and_description" =>
                "OFFICIAL RECEIPTS (Branch Copy)",
                "record_series_title_and_description_1" =>
                "Special Bank Receipt-Other Agencies (LBP Copy)",
                "active" => "2",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:47:51",
                "updated_at" => "2025-02-05 22:47:51",
            ],
            [
                "id" => "88",
                "item_number" => "122",
                "record_series_title_and_description" =>
                "OVERSEAS FILIPINO ACCOUNT FILES",
                "record_series_title_and_description_1" =>
                "Certification\\nKnow-Your-Client\\nOpening\\nUpdating\\nLBP Overseas Filipino Customer Information Sheet\\nOriginal\\nScanned",
                "active" => "0",
                "storage" => "4",
                "remarks" => "After account closure",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:48:19",
                "updated_at" => "2025-02-05 22:48:19",
            ],
            [
                "id" => "89",
                "item_number" => "123",
                "record_series_title_and_description" =>
                "PANTAWID PAMILYANG PILIPINO PROGRAM (4Ps) FILES",
                "record_series_title_and_description_1" =>
                "Acknowledgement Receipt\\nConsolidated Order of Payment\\nSchedule/List of Paid Beneficiaries (CCT Pay-Out)",
                "active" => "3",
                "storage" => "7",
                "remarks" => "Provided post audited",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:48:49",
                "updated_at" => "2025-02-05 22:48:49",
            ],
            [
                "id" => "90",
                "item_number" => "124",
                "record_series_title_and_description" =>
                "PHILIPPINE VETERANS AFFAIRS OFFICE (PVAO) FILES",
                "record_series_title_and_description_1" =>
                "Summary of PVAO Regular Pension for the Month\\nSummary of PVAO Total Administrative Disability\\nPension for the Month",
                "active" => "1",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:49:13",
                "updated_at" => "2025-02-05 22:49:13",
            ],
            [
                "id" => "91",
                "item_number" => "125",
                "record_series_title_and_description" =>
                "PHOTOCOPIES OF U S. DOLLAR AND OTHER FOREIGN CURRENCY NOTES FOR COUNTERFEIT VERIFICATION",
                "record_series_title_and_description_1" => null,
                "active" => "1",
                "storage" => "4",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:49:38",
                "updated_at" => "2025-02-05 22:49:38",
            ],
            [
                "id" => "92",
                "item_number" => "126",
                "record_series_title_and_description" =>
                "PROPOSAL FOR CONSTRUCTION/RENOVATION/ LEASE RELOCATION OF BRANCH SITE",
                "record_series_title_and_description_1" => null,
                "active" => "2",
                "storage" => "5",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:49:55",
                "updated_at" => "2025-02-05 22:49:55",
            ],
            [
                "id" => "93",
                "item_number" => "127",
                "record_series_title_and_description" =>
                "RECEIPTS FOR COLLECTION ITEMS - OUTWARD",
                "record_series_title_and_description_1" => null,
                "active" => "0",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:50:23",
                "updated_at" => "2025-02-05 22:50:23",
            ],
            [
                "id" => "94",
                "item_number" => "128",
                "record_series_title_and_description" => "REGISTERS",
                "record_series_title_and_description_1" =>
                "Account Number\\nCard Number",
                "active" => "99999999",
                "storage" => "0",
                "remarks" => null,
                "has_condition" => "0",
                "created_at" => "2025-02-05 22:52:55",
                "updated_at" => "2025-02-05 22:52:55",
            ],
            [
                "id" => "95",
                "item_number" => "129",
                "record_series_title_and_description" =>
                "REGISTRIES OF MANAGER\\\'S CHECK/GIFT CHECK/DEMAND DRAFT",
                "record_series_title_and_description_1" => null,
                "active" => "3",
                "storage" => "7",
                "remarks" => "After date of last entry",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:53:28",
                "updated_at" => "2025-02-05 22:53:28",
            ],
            [
                "id" => "96",
                "item_number" => "130A",
                "record_series_title_and_description" => "REPORTS",
                "record_series_title_and_description_1" =>
                "Automated Teller Machine (ATM) System Generated\\nATM Transmittal\\nAutomated ATM Reconciliation System (AARS) -\\nDaily\\nATM Cash Proofsheet/Cash Count Sheet\\nATM Checklist\\nElectronic Journal Daily Reading\\nLists of Reconciliation Items\\nConsolidated\\nTagged\\nUnresolved",
                "active" => "2",
                "storage" => "3",
                "remarks" => "Provided audited",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:55:22",
                "updated_at" => "2025-02-05 22:55:22",
            ],
            [
                "id" => "97",
                "item_number" => "130B",
                "record_series_title_and_description" => "REPORTS",
                "record_series_title_and_description_1" =>
                "Automated Teller Machine (ATM) Transaction and\\nActivity\\nCash Count Sheet\\nCash-ln-Vault Summary\\nConsolidated ATM Cash Flow\\nList of Retained Cards\\nSystematics Report (printed)\\nAccount with Negative Balance\\nAccount with Zero Balance (ST/IM)\\nAccumulation of Totals\\nDemand Deposit Account (DDA)\\nModified Disbursement Scheme (MDS).\\nSystematics Report (printed)\\nAccumulation of Totals\\nSavings Account (SA)\\nTime Deposit (CD)\\nAgrarian Reform Receivables System\\nFully Paid Account and Other Basic Data\\nList of Agrarian Reform Beneficiaries (ARBs)\\nwith Foreclosable Account\\nNon-Monetary Transaction\\nOutstanding Agrarian Reform Receivable\\n(ARR) by Movement\\nSummary of Foreclosed Lot\\n\\nProvided audited\\n\\nATM\\nEntered Interbranch Transaction\\nCards Issued/Reissued\\nPIN Mailers Issued\\nBalance Run-Up\\nBills Payment Journal\\nClearing Items (Interbranch Transaction)\\nClosed Accounts\\nClosed Today\\nConsolidated Daily Savings Deposit Account\\n(SDA) Balance Run-Up\\nConsolidated Unutilized Notice of Cash Allocation\\n(NCA)\\nCurrent Account (ACIC File Maintenance)\\nCustomer Information System/Central Liability\\nSystem (CIS/CLS)\\nException Item\\nData Extraction for Symbols\\nBalances\\nSymbols Extraction\\nDaily Balance Run-Up\\nDaily Callbacking Activity (DCA) Report, Online\\n& ATM-entered\\nDeduction List\\nDormant Account Activity\\nDormant Activity\\nElectronic Payment Collection Journal\\nElectronic Tax Payment System (ETPS)\\nEmployee Transaction\\nESP Documentary Stamp Reports\\nFCDU Accumulation of CD Totals\\nFile Maintenance Journal\\nFloat Schedule\\nFund Transfer (Phone Banking)\\nJournal\\nDestination\\nSource\\nMaintenance\\nService Charge\\nInterbranch Transaction Online System (IBTOLS)\\nConsolidated Reconciliation Statement\\nDaily Report on Cancelled/Deleted\\nTransactions\\nItems for Responding\\nItems Originated Not Yet Responded\\nSystematics Report (printed)\\nIMPACS Balance Run-Up\\nIncoming Electronic Money Transfer\\nInterest/Balance of Accounts\\nInterest Bearing Current Account (IBCA)\\nIBCA Balance Run-Up\\nInterest Expense\\nInterest Paid (ESP/HYSA)\\nLapsed Transfer Journal\\nLivelihood Loan System (LLS)\\nLoan Adjustment\\nPayment Transactions\\nReleased Transaction\\nSchedule\\nAmount Due and Collection\\nCredit Life Insurance\\nLivelihood Loan\\nOutstanding Loan\\nPast Due Account\\nSummary of Loan Availer\\nTransaction Posting Summary\\nMaintenance Journal\\nMaintenance Reject\\nMaturing HYSA Deposit\\nPDIC Summary\\nPhilippine Peso/US Dollar Online - Entered\\nInterbranch Transaction\\nPhone Access: Check Request Schedule\\nPIN Mailers Issued Report\\nPosting Reject Journal\\nProcessing Recap (CA,SA, CTD)\\nProjected CD Maturities Today\\nRenewal/Roll-over Report\\nReport on Escheat Account\\nRetail Treasury Bonds (RTB)\\nConsolidated Sales\\nDaily Summary of Transaction\\nSavings Transaction Journal\\nSavings Trial Balance/Transaction Journal\\nSchedule of Time Deposits Classified by Maturity\\n& Rate\\nSDA Account: Daily Transaction Journal\\nSignificant Balance Change Report\\nStatement\\nAccount\\nCurrent Year\\nPrevious Year\\nNegotiated Check\\nCurrent Year\\nPrevious Year\\nStop/Hold/Pledge Journal (CA/SA)\\nStop/Hold/Pledge Maintenance (CA/SA)\\nSummary of CTD FCDU Deposit\\nSummary Report\\nForeign Exchange (FX) Charge\\nInterbranch Transaction\\nweAccess Checkbook Reorder\\nSystematics Report (printed)\\nSweep Statistics (Outstanding Loans by Loan\\nStatus)\\nTop BIR/BOC Collections\\nTop Ten Report\\nTransaction Exception (BET/Current - Regular)\\nTransaction Total Reports/Summary (CA/SA)\\nWeekly Schedule of Check Request\\nTransmittal\\nCCVS Balancing Summary/Transmittal Sheet\\nfrom Central Clearing Department\\nDaily Transaction Transmittal Sheet to\\nAccounting Center\\nElectronic Check Clearing System\\nTransmittal List of Outward Check Daily Report\\nwith Photocopy of Check",
                "active" => "1",
                "storage" => "0",
                "remarks" => "Provided audited",
                "has_condition" => "1",
                "created_at" => "2025-02-05 22:58:41",
                "updated_at" => "2025-02-05 22:58:41",
            ],
        ];

        foreach ($rds as $r) {
            RecordsDispositionSchedule::create([
                "item_number" => $r["item_number"],
                "record_series_title_and_description" =>
                $r["record_series_title_and_description"],
                "record_series_title_and_description_1" => $r["record_series_title_and_description_1"],
                "active" => $r["active"],
                "storage" => $r["storage"],
                "remarks" => $r["remarks"],
                "has_condition" => $r["has_condition"],
            ]);
        }
    }
}
